import type { CollectionBeforeChangeHook, PayloadRequest } from 'payload'
import type { Category, Post } from '../../../payload-types'

type PayloadInstance = PayloadRequest['payload']

type SiteSettingsCache = {
  siteName: string
  cachedAt: number
}

const CACHE_TTL_MS = 5 * 60 * 1000
let siteSettingsCache: SiteSettingsCache | null = null

async function getSiteName(payload: PayloadInstance): Promise<string> {
  const now = Date.now()
  if (!siteSettingsCache || now - siteSettingsCache.cachedAt > CACHE_TTL_MS) {
    const siteSettings = await payload.findGlobal({ slug: 'site-settings' })
    siteSettingsCache = {
      siteName: siteSettings?.siteName ?? '',
      cachedAt: now,
    }
  }
  return siteSettingsCache.siteName
}

async function fetchFirstCategoryTitle(
  categories: (number | Category)[] | null | undefined,
  payload: PayloadInstance,
): Promise<string | null> {
  if (!categories?.length) return null
  const first = categories[0]
  if (typeof first !== 'number') return first.title ?? null
  const result = await payload.find({
    collection: 'categories',
    where: { id: { equals: first } },
    limit: 1,
    depth: 0,
  })
  return result.docs[0]?.title ?? null
}

async function fetchAllCategoryTitles(
  categories: (number | Category)[] | null | undefined,
  payload: PayloadInstance,
): Promise<string[]> {
  if (!categories?.length) return []
  const ids = categories.filter((c): c is number => typeof c === 'number')
  const populated = categories.filter((c): c is Category => typeof c !== 'number')
  const populatedTitles = populated.map((c) => c.title).filter((t): t is string => Boolean(t))
  if (ids.length === 0) return populatedTitles
  const result = await payload.find({
    collection: 'categories',
    where: { id: { in: ids } },
    limit: ids.length,
    depth: 0,
  })
  return [...populatedTitles, ...result.docs.map((c) => c.title).filter((t): t is string => Boolean(t))]
}

// New format: "{postTitle} | {firstCategory} | {siteName}"
function buildMetaTitle(postTitle: string, firstCategoryTitle: string | null, siteName: string): string {
  return [postTitle, firstCategoryTitle, siteName || undefined]
    .filter((s): s is string => Boolean(s))
    .join(' | ')
}

// Old format (pre-migration): "{siteName} | {postTitle}" or "{siteName} | {postTitle} | {cat1, cat2}"
function buildOldMetaTitle(siteName: string, postTitle: string, allCategoryTitles: string[]): string {
  const base = siteName ? `${siteName} | ${postTitle}` : postTitle
  return allCategoryTitles.length ? `${base} | ${allCategoryTitles.join(', ')}` : base
}

/**
 * Generates meta.title as "{Post Title} | {First Category} | {Site Name}" on every save.
 *
 * Format rationale: Google weights terms left-to-right, so the most specific signal
 * (the post title, which should naturally contain the primary keyword) comes first.
 * One category provides topical context; site name anchors the brand at the end.
 *
 * Override detection: compares the incoming meta.title against what was auto-generated
 * from the previously saved document. If they differ, the editor manually changed it
 * and we leave it alone. Recognises both the old ("{siteName} | {title} | {cats}") and
 * new formats so existing posts are migrated automatically on their next save.
 *
 * Site name is cached for 5 minutes to avoid a DB round-trip on every 100ms autosave.
 */
export const syncMetaTitle: CollectionBeforeChangeHook<Post> = async ({
  data,
  originalDoc,
  req: { payload },
}) => {
  if (!data.title) return data

  const siteName = await getSiteName(payload)

  if (originalDoc?.title) {
    const originalCategoryTitles = await fetchAllCategoryTitles(originalDoc.categories, payload)
    const currentTitle = (data.meta?.title as string | undefined) ?? ''

    const lastAutoGeneratedOld = buildOldMetaTitle(siteName, originalDoc.title, originalCategoryTitles)
    const lastAutoGeneratedNew = buildMetaTitle(
      originalDoc.title,
      originalCategoryTitles[0] ?? null,
      siteName,
    )

    const isAutoMode =
      !currentTitle ||
      currentTitle === lastAutoGeneratedOld ||
      currentTitle === lastAutoGeneratedNew

    if (!isAutoMode) return data
  }

  const firstCategoryTitle = await fetchFirstCategoryTitle(data.categories, payload)
  const metaTitle = buildMetaTitle(data.title as string, firstCategoryTitle, siteName)

  return {
    ...data,
    meta: {
      ...data.meta,
      title: metaTitle,
    },
  }
}
