import type { CollectionBeforeChangeHook } from 'payload'
import type { Post } from '../../../payload-types'
import { extractLexicalText } from '../../../utilities/extractLexicalText'

const META_DESCRIPTION_MAX_LENGTH = 160

/**
 * Auto-generates meta.description from the post body on every save.
 *
 * Manual-edit detection (mirrors syncTitleToSlug's override pattern):
 * Compares the currently stored description against what auto-generation
 * would have produced from the last-saved content (originalDoc.content).
 * If they match → still in auto-mode → overwrite with new value.
 * If they differ → user manually edited it → leave it alone.
 *
 * Clicking the SEO tab's "Auto Generate" link resets the description back
 * to the auto-generated value, which makes them match again on the next
 * save, restoring auto-mode.
 */
export const syncContentToMetaDescription: CollectionBeforeChangeHook<Post> = ({
  data,
  originalDoc,
}) => {
  if (!data.content?.root) return data

  // What auto-generation would have produced from the last saved content.
  // If currentDescription matches this, the description is still in auto-mode.
  const lastAutoGenerated = originalDoc?.content?.root
    ? extractLexicalText(originalDoc.content.root).substring(0, META_DESCRIPTION_MAX_LENGTH).trim()
    : ''

  const currentDescription = (data.meta?.description as string | undefined) ?? ''

  // Non-empty description that differs from last auto-generated → user manually edited it.
  if (currentDescription && currentDescription !== lastAutoGenerated) return data

  const newDescription = extractLexicalText(data.content.root)
    .substring(0, META_DESCRIPTION_MAX_LENGTH)
    .trim()

  if (!newDescription) return data

  return {
    ...data,
    meta: { ...data.meta, description: newDescription },
  }
}
